# Generated by Django 4.1.3 on 2022-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='location',
            field=models.CharField(default='Bulgaria', max_length=30),
            preserve_default=False,
        ),
    ]
