# Generated by Django 4.1.3 on 2022-12-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_first_name_alter_appuser_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'permissions': (('can_approve_auction', 'Can approve auction'),)},
        ),
    ]
