# Generated by Django 4.1.3 on 2022-11-20 16:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('item_photo', models.URLField()),
                ('approximate_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20)])),
                ('description', models.TextField(max_length=300)),
                ('specifications', models.TextField(max_length=200)),
                ('condition', models.CharField(choices=[('unused', 'Unused'), ('very_good', 'Very good'), ('good', 'Good'), ('damaged', 'Damaged')], max_length=9)),
                ('history', models.TextField(max_length=300)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
