# Generated by Django 4.1.3 on 2022-11-20 19:21

import auction.items.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, upload_to='item_photo/', validators=[auction.items.validators.validate_file_less_than_5mb]),
        ),
    ]
